<?php
require __DIR__.'/config.php'; require_role('admin');
$msg=null;
if($_SERVER['REQUEST_METHOD']==='POST' && ($_POST['action']??'')==='service'){
 $title=trim($_POST['title']); $slug=slugify($title); $stmt=$db->prepare('INSERT INTO services(title,slug,short_description,description,price,commission_rate) VALUES(?,?,?,?,?,?)'); $stmt->execute([$title,$slug,trim($_POST['short_description']),trim($_POST['description']),max(0,(float)$_POST['price']),max(0,min(100,(float)$_POST['commission_rate']))]); $msg='Servizio creato.';
}
if($_SERVER['REQUEST_METHOD']==='POST' && ($_POST['action']??'')==='partner'){
 $name=trim($_POST['name']); $slug=slugify($name).'-'.substr(bin2hex(random_bytes(3)),0,6); $stmt=$db->prepare('INSERT INTO users(name,email,password,role,slug,phone,whatsapp,company) VALUES(?,?,?,?,?,?,?,?)'); $stmt->execute([$name,trim($_POST['email']),password_hash($_POST['password'],PASSWORD_DEFAULT),'partner',$slug,trim($_POST['phone']),trim($_POST['whatsapp']),trim($_POST['company'])]); $msg='Partner creato.';
}
$services=$db->query('SELECT * FROM services ORDER BY id DESC')->fetchAll(); $partners=$db->query("SELECT * FROM users WHERE role='partner' ORDER BY id DESC")->fetchAll();
layout_start('Admin');?><div class="container"><h1>Admin Dashboard</h1><?php if($msg) echo '<div class="card">'.e($msg).'</div>'; ?><div class="grid"><div class="card"><div class="muted">Servizi</div><div class="stat"><?php echo count($services);?></div></div><div class="card"><div class="muted">Partner</div><div class="stat"><?php echo count($partners);?></div></div><div class="card"><div class="muted">Commissione standard</div><div class="stat">40%</div></div></div><div class="card"><h2>Nuovo servizio</h2><form method="post"><input type="hidden" name="action" value="service"><label>Nome</label><input name="title" required><label>Descrizione breve</label><input name="short_description"><label>Descrizione completa</label><textarea name="description" rows="6" required></textarea><div class="grid"><div><label>Prezzo (€)</label><input type="number" step="0.01" name="price" required></div><div><label>Commissione (%)</label><input type="number" step="0.01" name="commission_rate" value="40" required></div></div><button class="btn">Crea servizio</button></form></div><div class="card"><h2>Servizi</h2><table><tr><th>Servizio</th><th>Prezzo</th><th>Commissione</th><th>Pagina</th></tr><?php foreach($services as $s):?><tr><td><strong><?php echo e($s['title']);?></strong><br><span class="muted"><?php echo e($s['short_description']);?></span></td><td>€ <?php echo number_format((float)$s['price'],2,',','.');?></td><td><?php echo e((string)$s['commission_rate']);?>%</td><td><a href="service.php?id=<?php echo (int)$s['id'];?>" target="_blank">Apri</a></td></tr><?php endforeach;?></table></div><div class="card"><h2>Crea partner</h2><form method="post"><input type="hidden" name="action" value="partner"><div class="grid"><div><label>Nome</label><input name="name" required></div><div><label>Email</label><input type="email" name="email" required></div></div><div class="grid"><div><label>Password iniziale</label><input type="password" name="password" required></div><div><label>Azienda</label><input name="company"></div><div><label>Telefono</label><input name="phone"></div><div><label>WhatsApp</label><input name="whatsapp"></div></div><button class="btn">Crea partner</button></form></div><div class="card"><h2>Partner</h2><table><tr><th>Nome</th><th>Contatto</th><th>Landing</th></tr><?php foreach($partners as $p):?><tr><td><?php echo e($p['name']);?></td><td><?php echo e($p['email']);?></td><td><a href="partner.php" >Dashboard</a></td></tr><?php endforeach;?></table></div></div><?php layout_end();?>
