<?php
require __DIR__.'/config.php';
$db->exec('CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, password TEXT NOT NULL, role TEXT NOT NULL DEFAULT "partner", slug TEXT NOT NULL UNIQUE, phone TEXT, whatsapp TEXT, company TEXT, bio TEXT, avatar TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)');
$db->exec('CREATE TABLE IF NOT EXISTS services (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, short_description TEXT, description TEXT NOT NULL, price REAL NOT NULL DEFAULT 0, commission_rate REAL NOT NULL DEFAULT 40, min_price REAL NOT NULL DEFAULT 0, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)');
$db->exec('CREATE TABLE IF NOT EXISTS landing_pages (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, service_id INTEGER NOT NULL, slug TEXT NOT NULL UNIQUE, headline TEXT, subheadline TEXT, cta_text TEXT DEFAULT "Richiedi una consulenza", custom_description TEXT, theme TEXT DEFAULT "dark", published INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY(service_id) REFERENCES services(id) ON DELETE CASCADE)');
$db->exec('CREATE TABLE IF NOT EXISTS leads (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, service_id INTEGER NOT NULL, landing_page_id INTEGER, name TEXT NOT NULL, email TEXT, phone TEXT, message TEXT, status TEXT NOT NULL DEFAULT "new", source TEXT DEFAULT "landing", ip TEXT, user_agent TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(service_id) REFERENCES services(id), FOREIGN KEY(landing_page_id) REFERENCES landing_pages(id))');
$db->exec('CREATE TABLE IF NOT EXISTS sales (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, service_id INTEGER NOT NULL, lead_id INTEGER, amount REAL NOT NULL, commission_rate REAL NOT NULL DEFAULT 40, commission_amount REAL NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT "pending", created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(service_id) REFERENCES services(id), FOREIGN KEY(lead_id) REFERENCES leads(id))');
$db->exec('CREATE TABLE IF NOT EXISTS sales_guides (id INTEGER PRIMARY KEY AUTOINCREMENT, service_id INTEGER NOT NULL UNIQUE, opening TEXT, questions TEXT, objections TEXT, whatsapp_script TEXT, phone_script TEXT, email_script TEXT, follow_up TEXT, dont_say TEXT, FOREIGN KEY(service_id) REFERENCES services(id) ON DELETE CASCADE)');
foreach (["ALTER TABLE users ADD COLUMN avatar TEXT","ALTER TABLE services ADD COLUMN min_price REAL NOT NULL DEFAULT 0","ALTER TABLE landing_pages ADD COLUMN custom_description TEXT","ALTER TABLE landing_pages ADD COLUMN theme TEXT DEFAULT 'dark'","ALTER TABLE leads ADD COLUMN source TEXT DEFAULT 'landing'","ALTER TABLE leads ADD COLUMN ip TEXT","ALTER TABLE leads ADD COLUMN user_agent TEXT","ALTER TABLE sales ADD COLUMN commission_rate REAL NOT NULL DEFAULT 40","ALTER TABLE sales ADD COLUMN commission_amount REAL NOT NULL DEFAULT 0","ALTER TABLE sales_guides ADD COLUMN email_script TEXT","ALTER TABLE sales_guides ADD COLUMN follow_up TEXT","ALTER TABLE sales_guides ADD COLUMN dont_say TEXT"] as $sql){try{$db->exec($sql);}catch(Throwable $e){}}
if ((int)$db->query("SELECT COUNT(*) FROM users WHERE role='admin'")->fetchColumn()===0){$st=$db->prepare('INSERT INTO users(name,email,password,role,slug) VALUES(?,?,?,?,?)');$st->execute(['Administrator','admin@example.com',password_hash('ChangeMe123!',PASSWORD_DEFAULT),'admin','admin']);}
if ((int)$db->query('SELECT COUNT(*) FROM services')->fetchColumn()===0){$st=$db->prepare('INSERT INTO services(title,slug,short_description,description,price,commission_rate,min_price) VALUES(?,?,?,?,?,?,?)');$st->execute(['Automatizzazione Social Media','automatizzazione-social-media','Automatizza la gestione dei tuoi canali social.','Piattaforma personalizzabile per automatizzare pubblicazione, gestione contenuti e flussi social.',2500,40,1800]);}
layout_start('Installazione');?><div class="container"><div class="card"><h1>Partner Sales Hub</h1><p>Database creato o aggiornato correttamente.</p><p><strong>Admin iniziale:</strong> admin@example.com<br><strong>Password:</strong> ChangeMe123!</p><p class="muted">Cambia la password e rimuovi install.php dal server.</p><a class="btn" href="index.php">Vai al login</a></div></div><?php layout_end(); ?>
