<?php
require __DIR__.'/config.php'; require_role('partner');
$u=user(); $id=(int)($_GET['id']??0);
$q=$db->prepare('SELECT lp.*,s.title service_title,s.slug service_slug,s.short_description,s.description,s.price,s.commission_rate FROM landing_pages lp JOIN services s ON s.id=lp.service_id WHERE lp.id=? AND lp.user_id=?');
$q->execute([$id,$u['id']]); $p=$q->fetch(); if(!$p){http_response_code(404);exit('Landing non trovata');}
$msg=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
 $st=$db->prepare('UPDATE landing_pages SET headline=?,subheadline=?,cta_text=?,custom_description=?,theme=?,published=? WHERE id=? AND user_id=?');
 $st->execute([trim($_POST['headline']),trim($_POST['subheadline']),trim($_POST['cta_text']),trim($_POST['custom_description']),in_array($_POST['theme']??'dark',['dark','light','blue'],true)?$_POST['theme']:'dark',isset($_POST['published'])?1:0,$id,$u['id']]);
 $msg='Landing aggiornata.'; $q->execute([$id,$u['id']]); $p=$q->fetch();
}
layout_start('Editor Landing');?><div class="container"><div style="display:flex;justify-content:space-between;gap:15px;align-items:center"><div><h1>Landing Page Builder</h1><p class="muted"><?php echo e($p['service_title']);?></p></div><a class="btn secondary" target="_blank" href="p.php?u=<?php echo urlencode($u['slug']);?>&s=<?php echo urlencode($p['service_slug']);?>">Visualizza pagina</a></div><?php if($msg)echo '<div class="card">'.e($msg).'</div>';?><div class="grid"><div class="card"><h2>Contenuto</h2><form method="post"><label>Titolo principale</label><input name="headline" value="<?php echo e($p['headline']?:$p['service_title']);?>" required><label>Sottotitolo</label><textarea name="subheadline" rows="3"><?php echo e($p['subheadline']);?></textarea><label>Descrizione personalizzata</label><textarea name="custom_description" rows="8" placeholder="Lascia vuoto per usare la descrizione del servizio."><?php echo e($p['custom_description']??'');?></textarea><label>Testo CTA</label><input name="cta_text" value="<?php echo e($p['cta_text']?:'Richiedi una consulenza');?>"><label>Tema</label><select name="theme"><option value="dark" <?php echo ($p['theme']??'dark')==='dark'?'selected':'';?>>Dark</option><option value="light" <?php echo ($p['theme']??'')==='light'?'selected':'';?>>Light</option><option value="blue" <?php echo ($p['theme']??'')==='blue'?'selected':'';?>>Blue</option></select><label><input style="width:auto" type="checkbox" name="published" <?php echo $p['published']?'checked':'';?>> Pubblicata</label><br><br><button class="btn">Salva modifiche</button></form></div><div class="card"><h2>Anteprima contenuti</h2><p><strong><?php echo e($p['headline']?:$p['service_title']);?></strong></p><p><?php echo e($p['subheadline']);?></p><p>Prezzo: <strong>€ <?php echo number_format((float)$p['price'],2,',','.');?></strong></p><p>Commissione partner: <strong><?php echo e((string)$p['commission_rate']);?>%</strong></p><hr><p class="muted">Link pubblico</p><code>p.php?u=<?php echo e($u['slug']);?>&s=<?php echo e($p['service_slug']);?></code><h3>Contatto partner</h3><p><?php echo e($u['name']);?><?php echo $u['company']?' · '.e($u['company']):'';?></p><p><?php echo e($u['phone']);?> <?php echo $u['whatsapp']?'· WhatsApp '.e($u['whatsapp']):'';?></p></div></div></div><?php layout_end();?>
