<?php
require __DIR__.'/config.php';
$uStmt=$db->prepare("SELECT * FROM users WHERE slug=? AND role='partner'");$uStmt->execute([trim($_GET['u']??'')]);$u=$uStmt->fetch();
$sStmt=$db->prepare('SELECT * FROM services WHERE slug=? AND active=1');$sStmt->execute([trim($_GET['s']??'')]);$s=$sStmt->fetch();
if(!$u||!$s){http_response_code(404);exit('Pagina non trovata');}
$pStmt=$db->prepare('SELECT * FROM landing_pages WHERE user_id=? AND service_id=? AND published=1 LIMIT 1');$pStmt->execute([$u['id'],$s['id']]);$p=$pStmt->fetch();if(!$p){http_response_code(404);exit('Landing page non pubblicata');}
if($_SERVER['REQUEST_METHOD']==='POST'){$email=trim($_POST['email']??'');$phone=trim($_POST['phone']??'');$name=trim($_POST['name']??'');if($name&&($email||$phone)){$st=$db->prepare('SELECT id FROM leads WHERE user_id=? AND service_id=? AND ((email<>"" AND email=?) OR (phone<>"" AND phone=?)) LIMIT 1');$st->execute([$u['id'],$s['id'],$email,$phone]);$duplicate=$st->fetch();if(!$duplicate){$st=$db->prepare('INSERT INTO leads(user_id,service_id,landing_page_id,name,email,phone,message,source,ip,user_agent) VALUES(?,?,?,?,?,?,?,?,?,?)');$st->execute([$u['id'],$s['id'],$p['id'],$name,$email,$phone,trim($_POST['message']??''),'landing',$_SERVER['REMOTE_ADDR']??'',substr($_SERVER['HTTP_USER_AGENT']??'',0,500)]);} $thanks=true;}}
$desc=trim($p['custom_description']??'')?:$s['description'];$theme=$p['theme']??'dark';
layout_start($p['headline']?:$s['title']);?><div class="container"><div class="hero" style="<?php echo $theme==='light'?'background:#fff;color:#172033;border:1px solid #e6eaf0':($theme==='blue'?'background:linear-gradient(135deg,#1d4ed8,#0f172a)':'');?>"><span class="pill">Servizio digitale</span><h1><?php echo e($p['headline']?:$s['title']);?></h1><p><?php echo e($p['subheadline']?:$s['short_description']);?></p><h2>€ <?php echo number_format((float)$s['price'],2,',','.');?></h2><a class="btn" href="#contatto"><?php echo e($p['cta_text']?:'Richiedi una consulenza');?></a></div><div class="card"><h2>La soluzione</h2><p><?php echo nl2br(e($desc));?></p></div><div class="card"><h2>Parla con <?php echo e($u['name']);?></h2><?php if($u['company'])echo '<p class="muted">'.e($u['company']).'</p>';if($u['bio'])echo '<p>'.nl2br(e($u['bio'])).'</p>';if($u['phone'])echo '<p>☎ '.e($u['phone']).'</p>';if($u['whatsapp'])echo '<p>💬 '.e($u['whatsapp']).'</p>';?><div id="contatto"><?php if(!empty($thanks)):?><p><strong>Richiesta ricevuta.</strong> <?php echo e($u['name']);?> ti ricontatterà presto.</p><?php else:?><form method="post"><label>Nome</label><input name="name" required><label>Email</label><input type="email" name="email"><label>Telefono</label><input name="phone"><label>Di cosa hai bisogno?</label><textarea name="message" rows="5"></textarea><button class="btn">Invia richiesta</button></form><p class="muted">Inserisci almeno email oppure telefono.</p><?php endif;?></div></div></div><?php layout_end();?>
