<?php
require __DIR__.'/config.php'; require_role('partner');
$u=user(); $msg=null;
if($_SERVER['REQUEST_METHOD']==='POST' && ($_POST['action']??'')==='landing'){
 $serviceId=(int)$_POST['service_id']; $s=$db->prepare('SELECT * FROM services WHERE id=? AND active=1'); $s->execute([$serviceId]); $service=$s->fetch();
 if($service){$base=slugify($u['slug'].'-'.$service['slug']);$slug=$base.'-'.substr(bin2hex(random_bytes(2)),0,4);$stmt=$db->prepare('INSERT INTO landing_pages(user_id,service_id,slug,headline,subheadline) VALUES(?,?,?,?,?)');$stmt->execute([$u['id'],$serviceId,$slug,$service['title'],$service['short_description']]);$msg='Landing page creata: p.php?u='.urlencode($u['slug']).'&s='.urlencode($service['slug']);}
}
$services=$db->query('SELECT * FROM services WHERE active=1 ORDER BY id DESC')->fetchAll();
$stmt=$db->prepare('SELECT lp.*,s.title,s.slug service_slug FROM landing_pages lp JOIN services s ON s.id=lp.service_id WHERE lp.user_id=? ORDER BY lp.id DESC');$stmt->execute([$u['id']]);$pages=$stmt->fetchAll();
$stmt=$db->prepare('SELECT l.*,s.title FROM leads l JOIN services s ON s.id=l.service_id WHERE l.user_id=? ORDER BY l.id DESC');$stmt->execute([$u['id']]);$leads=$stmt->fetchAll();
layout_start('Partner Dashboard');?><div class="container"><h1>Ciao <?php echo e($u['name']);?> 👋</h1><?php if($msg) echo '<div class="card">'.e($msg).'</div>'; ?><div class="grid"><div class="card"><div class="muted">Landing Pages</div><div class="stat"><?php echo count($pages);?></div></div><div class="card"><div class="muted">Lead</div><div class="stat"><?php echo count($leads);?></div></div><div class="card"><div class="muted">Commissione base</div><div class="stat">40%</div></div></div><div class="card"><h2>Crea Landing Page</h2><form method="post"><input type="hidden" name="action" value="landing"><label>Scegli servizio</label><select name="service_id" required><?php foreach($services as $s):?><option value="<?php echo (int)$s['id'];?>"><?php echo e($s['title']);?> — € <?php echo number_format((float)$s['price'],2,',','.');?> — <?php echo e((string)$s['commission_rate']);?>%</option><?php endforeach;?></select><button class="btn">Genera Landing Page</button></form></div><div class="card"><h2>Le mie Landing Pages</h2><?php if(!$pages):?><p class="muted">Non hai ancora creato pagine.</p><?php else:?><table><tr><th>Servizio</th><th>Link</th></tr><?php foreach($pages as $p):?><tr><td><?php echo e($p['title']);?></td><td><a href="p.php?u=<?php echo urlencode($u['slug']);?>&s=<?php echo urlencode($p['service_slug']);?>" target="_blank">Apri landing</a></td></tr><?php endforeach;?></table><?php endif;?></div><div class="card"><h2>Lead ricevuti</h2><?php if(!$leads):?><p class="muted">Nessun lead ancora.</p><?php else:?><table><tr><th>Cliente</th><th>Servizio</th><th>Stato</th><th>Data</th></tr><?php foreach($leads as $l):?><tr><td><?php echo e($l['name']);?><br><?php echo e($l['email']);?></td><td><?php echo e($l['title']);?></td><td><span class="pill"><?php echo e($l['status']);?></span></td><td><?php echo e($l['created_at']);?></td></tr><?php endforeach;?></table><?php endif;?></div></div><?php layout_end();?>
